import test from 'node:test';
import assert from 'node:assert/strict';
import * as T from 'three';
import { createDocument } from '../src/shared/catalog';
import { mutateDocument } from '../src/shared/operations';
import { inspectScene } from '../src/shared/scene-inspection';
import { buildScene, disposeScene } from '../src/shared/scene-runtime';
import { boneWorld } from '../src/shared/scene-rigging';
import { documentSchema } from '../src/shared/schema';
import { interpolateNode } from '../src/shared/render';
function setup(){const doc=createDocument('3d','Puppy');doc.pages[0].nodes=[{id:'body',type:'model3d',name:'body',x:0,y:0,width:400,height:400,data:{geometry:'sphere'},scene:{position:[0,0,0],scale:[1,1,1]}}];return doc;}
function command(doc:ReturnType<typeof setup>,command:unknown){return mutateDocument(doc,[{op:'scene-command',pageId:doc.pages[0].id,command}]);}
test('remesh produces a closed surface and preserves original primitives',()=>{let doc=setup();doc.pages[0].nodes.push({...doc.pages[0].nodes[0],id:'head',scene:{position:[0,1,0],scale:[.7,.7,.7]}});const before=JSON.stringify(doc);const next=command(doc,{action:'remesh',nodeIds:['body','head'],outputId:'skin',resolution:16,symmetry:true});assert.equal(JSON.stringify(doc),before);assert.equal(next.pages[0].nodes[0].visible,false);const result=inspectScene(next).pages[0].nodes.find(n=>n.id==='skin')!;assert('triangles' in result&&result.triangles!>100);assert.deepEqual(result.issues,[]);assert.throws(()=>command(doc,{action:'remesh',nodeIds:['missing'],outputId:'skin'}));});
test('loft creates joint rings and closed caps with consistent winding',()=>{const next=command(setup(),{action:'loft',outputId:'leg',rings:[{center:[0,0,0],radius:.3},{center:[0,1,0],radius:.3},{center:[0,2,.2],radius:.2}],segments:12});const report=inspectScene(next).pages[0].nodes.find(n=>n.id==='leg')!;assert.deepEqual(report.issues,[]);});
test('auto weights normalize, skin responds to pose, playback preserves bind state',async()=>{let doc=command(setup(),{action:'convert',nodeId:'body'});doc=command(doc,{action:'rig-quadruped',nodeId:'body'});doc=command(doc,{action:'bind',nodeId:'body'});const mesh=doc.pages[0].nodes[0].scene!.mesh!;for(let i=0;i<mesh.positions.length/3;i++)assert(Math.abs(mesh.skinWeights!.slice(i*4,i*4+4).reduce((a,b)=>a+b,0)-1)<1e-6);const original=JSON.stringify(doc);doc=command(doc,{action:'clip',nodeId:'body',preset:'idle',duration:2});const before=JSON.stringify(doc);const {scene}=await buildScene(doc,0,.5);const skin=scene.getObjectByName('body') as T.SkinnedMesh;assert(skin.isSkinnedMesh);scene.updateMatrixWorld(true);skin.skeleton.update();let moved=0;for(let i=0;i<mesh.positions.length/3;i++){const a=new T.Vector3().fromArray(mesh.positions,i*3);if(skin.applyBoneTransform(i,a.clone()).distanceTo(a)>.00001)moved++;}assert(moved>0);assert.equal(JSON.stringify(doc),before);disposeScene(scene);assert.notEqual(original,before);});
test('IK moves endpoint toward local-space target',()=>{let doc=command(setup(),{action:'convert',nodeId:'body'});doc=command(doc,{action:'rig-quadruped',nodeId:'body'});const bones=doc.pages[0].nodes[0].scene!.bones!,end=bones.findIndex(b=>b.name==='frontLeftFoot'),origin=new T.Vector3().setFromMatrixPosition(boneWorld(bones)[end]),target=origin.clone().add(new T.Vector3(0,.2,.15));const next=command(doc,{action:'ik',nodeId:'body',endBone:'frontLeftFoot',target:target.toArray()});const result=new T.Vector3().setFromMatrixPosition(boneWorld(next.pages[0].nodes[0].scene!.bones!)[end]);assert(result.distanceTo(target)<origin.distanceTo(target));});
test('morph targets animate without mutating geometry; UV packing preserves skin/morph data',()=>{let doc=command(setup(),{action:'convert',nodeId:'body'});doc=command(doc,{action:'rig-quadruped',nodeId:'body'});doc=command(doc,{action:'bind',nodeId:'body'});doc=command(doc,{action:'morph',nodeId:'body',name:'blink',vertices:[1,2,3],delta:[0,-.2,0],weight:0});doc.timeline={duration:1,fps:30,tracks:[{id:'blink',nodeId:'body',keyframes:[{time:0,values:{'scene.morphWeights.blink':0}},{time:1,values:{'scene.morphWeights.blink':1}}]}]};assert.equal(interpolateNode(doc.pages[0].nodes[0],doc,.5).scene!.morphWeights!.blink,.5);const next=command(doc,{action:'uv-pack',nodeId:'body'}),mesh=next.pages[0].nodes[0].scene!.mesh!;assert.equal(mesh.uv!.length,mesh.positions.length/3*2);assert.equal(mesh.skinWeights!.length,mesh.positions.length/3*4);assert.equal(mesh.morphTargets![0].positions.length,mesh.positions.length);assert(documentSchema.safeParse(next).success);});
test('invalid operations are atomic and topology edits cannot silently invalidate rigs',()=>{const doc=command(setup(),{action:'convert',nodeId:'body'}),before=JSON.stringify(doc);assert.throws(()=>command(doc,{action:'morph',nodeId:'body',name:'oops',vertices:[999999],delta:[0,1,0]}));assert.equal(JSON.stringify(doc),before);assert.throws(()=>command(doc,{action:'bind',nodeId:'body'}));});

test('rigid accessories bake transforms, follow poses and inherit generated clips',async()=>{
  let doc=command(setup(),{action:'convert',nodeId:'body'});doc=command(doc,{action:'rig-quadruped',nodeId:'body'});doc.pages[0].nodes.push({id:'eye',name:'eye',type:'model3d',x:0,y:0,width:100,height:100,data:{geometry:'sphere'},scene:{position:[.4,.8,.5],scale:[.1,.1,.1]}});doc=command(doc,{action:'convert',nodeId:'eye'});doc=command(doc,{action:'attach',nodeId:'eye',rigNodeId:'body',bone:'head'});const eye=doc.pages[0].nodes[1];assert.equal(eye.scene!.scale![0],1);assert(Math.abs(eye.scene!.mesh!.positions[1]-.9)<1e-5);doc=command(doc,{action:'pose',nodeId:'body',bone:'head',rotation:[0,10,0]});assert.deepEqual(doc.pages[0].nodes[1].scene!.bones,doc.pages[0].nodes[0].scene!.bones);doc=command(doc,{action:'clip',nodeId:'body',preset:'idle'});assert.equal(doc.timeline!.tracks.length,2);
});

test('topology and paint reject invalid authoring order without partial changes',()=>{let doc=command(setup(),{action:'convert',nodeId:'body'});doc=command(doc,{action:'paint',nodeId:'body',uv:[.5,.5],radius:.1,color:'#ff0000'});const before=JSON.stringify(doc);assert.throws(()=>command(doc,{action:'uv-pack',nodeId:'body'}),/Clear texture paint/);assert.equal(JSON.stringify(doc),before);doc=command(doc,{action:'rig-quadruped',nodeId:'body'});doc=command(doc,{action:'bind',nodeId:'body'});assert.throws(()=>command(doc,{action:'relax',nodeId:'body'}),/topology/);});

test('triangle BVH remeshing reconstructs closed document meshes',()=>{let doc=setup();doc.pages[0].nodes[0].data={geometry:'box'};doc=command(doc,{action:'convert',nodeId:'body'});const next=command(doc,{action:'remesh',nodeIds:['body'],outputId:'retopo',resolution:16,symmetry:true});const report=inspectScene(next).pages[0].nodes.find(n=>n.id==='retopo')!;assert.deepEqual(report.issues,[]);assert('vertices' in report&&report.vertices!>30);});
