export function SceneDocumentation(){return <>
  <h2>Build an editable 3D character</h2><p>Open a 3D project and choose Character authoring. Human controls and agent tools use the same validated geometry, skeleton and animation data.</p>
  <ol><li><strong>Shape.</strong> Remesh unparented sphere primitives or closed document meshes into a continuous surface. Preview first; applying keeps source objects hidden. Use joint-ring lofts for controlled limb topology. Imported asset nodes need editable document geometry first.</li><li><strong>Rig.</strong> Create a quadruped skeleton, inspect its joints and adjust landmarks or bone positions for the model. Auto-bind weights, inspect the heatmap and smooth or mirror weights. Attach eyes and accessories to a named bone.</li><li><strong>Animate.</strong> Pose with FK or bounded IK, then add idle, wag or walk clips. Inspect contact and deformation across the timeline. Morph targets add editable expressions.</li><li><strong>Finish.</strong> Cut and pack UV islands, paint layered color, normal and roughness maps at 256–2048px and inspect topology/weights. Export GLB/glTF and reopen the file to verify meshes, skeletons, morph targets, textures and clips.</li></ol>
  <h2>Agent workflow</h2><p>Discover <code>sceneCommands</code> through <code>studio_capabilities</code> or <code>/api/schema</code>. WebMCP <code>studio_scene_command</code> accepts a page ID and command, previews by default, and applies with <code>preview:false</code>. <code>studio_inspect_scene</code> returns compact diagnostics at a requested time without transferring vertex buffers.</p>
  <p>Saved-state equivalents are REST GET/POST <code>/api/projects/:id/scene</code>, MCP <code>inspect_scene</code>/<code>author_scene</code>, and CLI <code>dsa scene inspect</code>/<code>dsa scene command</code>. Writes require the observed revision. CLI commands are available in the current source build; an older release archive may not include them.</p>
  <h2>What the tools check</h2><p>Reports flag degenerate triangles, boundary or non-manifold edges, inconsistent winding, unnormalized skin weights and severe edge stretching in sampled poses. They do not certify self-intersection freedom or animation quality. UV seams can intentionally split vertices.</p><p>Remeshing uses bounded surface sampling rather than semantic quad retopology. Quadruped landmarks and nearest-segment weights are editable starting points. One-shot IK uses mesh-local targets. Persistent two-bone contacts use world targets, bend poles, horizontal ground height, time ranges and rotation limits; inspect measured error for unreachable targets. Explicit UV islands use planar projection and need a distortion/overlap check. Color paint replaces the base-color map. Sculpt, edge splits and plane-cut loops preserve vertex attributes; legacy remesh/relax reject bound geometry. Save a mesh checkpoint before refinement.</p>
  <h2>Shared rigs, clips and repair</h2><p>Share skeleton with attachments explicitly converts compatible legacy copies to one rig reference. Named clip controls adjust speed, amplitude, loop count and blend without rewriting source keys. Later tracks blend over earlier tracks; outside clip intervals the stored pose applies. Joint gizmos edit rest or pose, and weight brushes support mirrored stamps, locked joints/vertices and heatmaps.</p>
  <p>Complete-animation diagnostics return issue IDs, affected vertices/faces and times, plus contact drift and floor penetration. Click a warning to select its region and pose; compare the next scan with the previous count. Informational coincident seam boundaries are distinguished from defects. Export Four angle views for actual PNGs around the saved camera target.</p>
  <h2>Recover long saves and exports</h2><p>Use durable operations with a stable ID: POST <code>/api/projects/:id/operations</code>, poll GET <code>/api/projects/:id/operations/:operationId</code>, then download <code>/result</code>. An uncertain response must reuse the same ID and payload. Jobs retain owner authorization and observed revisions; export pins the accepted document snapshot.</p><p>WebMCP <code>studio_start_save</code> returns immediately; poll the operation then use <code>studio_reconcile_save</code>. Network MCP exposes <code>start_operation</code>, <code>get_operation</code> and <code>get_operation_result</code>; CLI exposes <code>dsa operations start/status/result</code>. The editor Operations control recalls the latest ID. Save receipts and export artifacts remain private until project deletion. Live collaborative merging retains its separate merge contract.</p>
</>;}
