export function SceneDocumentation(){return <>
  <h2>Build an editable 3D character</h2><p>Open a 3D project and choose Character authoring. Human controls and agent tools use the same validated geometry, skeleton and animation data.</p>
  <ol><li><strong>Shape.</strong> Remesh unparented sphere primitives or closed document meshes into a continuous surface. Preview first; applying keeps source objects hidden. Use joint-ring lofts for controlled limb topology. Imported asset nodes need editable document geometry first.</li><li><strong>Rig.</strong> Create a quadruped skeleton, inspect its joints and adjust landmarks or bone positions for the model. Auto-bind weights, inspect the heatmap and smooth or mirror weights. Attach eyes and accessories to a named bone.</li><li><strong>Animate.</strong> Pose with FK or bounded IK, then add idle, wag or walk clips. Inspect contact and deformation across the timeline. Morph targets add editable expressions.</li><li><strong>Finish.</strong> Cut and pack UV islands, paint layered color, normal and roughness maps at 256–2048px and inspect topology/weights. Export GLB/glTF and reopen the file to verify meshes, skeletons, morph targets, textures and clips.</li></ol>
  <h2>Materials</h2><p>Select a 3D object to open <strong>Material</strong> in the inspector. The values persist on the object as <code>scene.material</code>, so the viewport, the raster exports and GLB read the same record.</p>
  <ul><li><strong>Presets</strong> are starting points: Matte (metalness 0, roughness 0.85), Ceramic (0, 0.2), Metal (1, 0.25) and Polished (0.9, 0.08).</li><li><strong>Material color</strong> takes a hex value or a theme token such as <code>$accent</code>. <strong>Metalness</strong> and <strong>roughness</strong> run from 0 to 1; the object's own data supplies the starting value, so the built-in 3D template begins at 0.25 and 0.25.</li><li><strong>Wireframe</strong> draws edges instead of surfaces. <strong>Double sided</strong> also renders back faces; keep it for open or imported single-surface meshes, since closed solids do not need it.</li><li>Stored vertex colors multiply the material color, and a painted base-color map replaces it.</li></ul>
  <p>Edit these in the inspector or with <code>update-node</code>. A <code>scene</code> object is replaced rather than merged, so read it first and send the fields you are not changing back unchanged.</p>
  <h2>Textures and UV paint</h2><p>Textures are owned project assets. Importing a PNG, JPEG or WebP in <strong>Color texture</strong> uploads it to the project and references it as <code>scene.material.textureAssetId</code>; previews and exports read that asset. An imported model that still carries its own texture offers its original model texture, and external media must be imported before cloud rendering.</p>
  <ol className="docs-numbered"><li><strong>Unwrap.</strong> Add seam edges and unwrap the islands, or use a mesh that already has UVs. Painting is rejected without them.</li><li><strong>Layer.</strong> Create a layer with a name and one map type — <code>color</code>, <code>normal</code> or <code>roughness</code> — plus opacity and visibility. A layer keeps its map type; edit the name, opacity or visibility instead. Up to eight layers persist per object.</li><li><strong>Paint.</strong> A stroke stores a UV point, a radius and a hex color, and a layer keeps at most 256. Strokes stay vector data in the document and are rasterized into the maps whenever the scene is built or exported.</li><li><strong>Resolution.</strong> Choose 256, 512, 1024 or 2048px. One resolution applies to every map on that object.</li><li><strong>Clear before changing UVs.</strong> Unwrapping refuses to run while strokes exist, because a painted color map replaces the imported base-color texture and would no longer line up.</li></ol>
  <p>The UV view draws the islands with an optional distortion tint. Red marks area stretch; it is not proof that islands do not overlap. A stroke sent without a layer writes to the legacy single color map, which has the same 256-stroke budget. GLB/glTF embeds the rasterized maps.</p>
  <h2>Lighting, camera and shadows</h2><p>Deselect every object to edit the page's <strong>Camera</strong> and <strong>Lighting</strong>; both live on the page as <code>page.scene</code>, so every object on it shares one view and one light. Change them in the inspector or with <code>update-page</code>.</p>
  <ul><li><strong>Camera:</strong> position, look-at target and field of view between 10° and 120°. <strong>Reset camera</strong> restores the saved default, and the four-view PNG export orbits the target stored here.</li><li><strong>Lighting:</strong> ambient intensity from 0 to 10, plus one directional light with position, intensity from 0 to 20 and color. The directional light casts shadows in the editor viewport; ambient light is directionless fill that casts none.</li></ul>
  <p>Defaults are a camera at <code>[5,4,7]</code> looking at <code>[0,0.5,0]</code> at 40°, ambient <code>2</code>, and a white directional light at <code>[3,6,4]</code> with intensity <code>4</code>. Add light before raising metalness: with a single light and no environment map, a metal surface has almost nothing to reflect and reads black.</p>
  <p>Raster exports reuse this camera, these lights and the materials without a shadow map, so an exported still can look flatter than the viewport. GLB/glTF carries geometry, materials, embedded maps and sampled animations; the directional light is written as <code>KHR_lights_punctual</code>, ambient light has no glTF equivalent, and a viewer without lights needs its own.</p>
  <h2>Agent workflow</h2><p>Discover <code>sceneCommands</code> through <code>studio_capabilities</code> or <code>/api/schema</code>. WebMCP <code>studio_scene_command</code> accepts a page ID and command, previews by default, and applies with <code>preview:false</code>. <code>studio_inspect_scene</code> returns compact diagnostics at a requested time without transferring vertex buffers.</p>
  <p>Saved-state equivalents are REST GET/POST <code>/api/projects/:id/scene</code>, MCP <code>inspect_scene</code>/<code>author_scene</code>, and CLI <code>dsa scene inspect</code>/<code>dsa scene command</code>. Writes require the observed revision. CLI commands are available in the current source build; an older release archive may not include them.</p>
  <h2>What the tools check</h2><p>Reports flag degenerate triangles, boundary or non-manifold edges, inconsistent winding, unnormalized skin weights and severe edge stretching in sampled poses. They do not certify self-intersection freedom or animation quality. UV seams can intentionally split vertices.</p><p>Remeshing uses bounded surface sampling rather than semantic quad retopology. Quadruped landmarks and nearest-segment weights are editable starting points. One-shot IK uses mesh-local targets. Persistent two-bone contacts use world targets, bend poles, horizontal ground height, time ranges and rotation limits; inspect measured error for unreachable targets. Explicit UV islands use planar projection and need a distortion/overlap check. Color paint replaces the base-color map. Sculpt, edge splits and plane-cut loops preserve vertex attributes; legacy remesh/relax reject bound geometry. Save a mesh checkpoint before refinement.</p>
  <h2>Shared rigs, clips and repair</h2><p>Share skeleton with attachments explicitly converts compatible legacy copies to one rig reference. Named clip controls adjust speed, amplitude, loop count and blend without rewriting source keys. Later tracks blend over earlier tracks; outside clip intervals the stored pose applies. Joint gizmos edit rest or pose, and weight brushes support mirrored stamps, locked joints/vertices and heatmaps.</p>
  <p>Complete-animation diagnostics return issue IDs, affected vertices/faces and times, plus contact drift and floor penetration. Click a warning to select its region and pose; compare the next scan with the previous count. Informational coincident seam boundaries are distinguished from defects and appear only in the first scan frame; warning locations remain time-indexed. Export Four angle views for actual PNGs around the saved camera target.</p>
  <h2>Recover long saves and exports</h2><p>Use durable operations with a stable ID: POST <code>/api/projects/:id/operations</code>, poll GET <code>/api/projects/:id/operations/:operationId</code>, then download <code>/result</code>. An uncertain response must reuse the same ID and payload. Jobs retain owner authorization and observed revisions; export pins the accepted document snapshot.</p><p>WebMCP <code>studio_start_save</code> returns immediately; poll the operation then use <code>studio_reconcile_save</code>. Network MCP exposes <code>start_operation</code>, <code>get_operation</code> and <code>get_operation_result</code>; CLI exposes <code>dsa operations start/status/result</code>. The editor Operations control recalls the latest ID. Save receipts and export artifacts remain private until project deletion. Live collaborative merging retains its separate merge contract.</p>
</>;}
