import JSZip from 'jszip';
import { z } from 'zod';
import type { Context } from 'hono';
import type { Env,Bindings } from '../types';
import type { ConnectorOperation } from '../../src/shared/connector-operations';
import { renderProjectExport } from '../exports';
import { limitedBytes } from '../providers';
import { githubSourcePath } from './github';
import { githubHeaders } from './github-auth';
import { nativeJson } from './native-transport';
import { beginConnectorObjectUpload,abandonConnectorObjectUpload } from '../connector-object-cleanup';
import { exportArtifact,readExportArtifact } from './google-export-artifacts';
import { inspectOperationVersions } from '../connector-operation-versions';
import { encrypt,fail } from '../security';
export const githubExportArguments=z.strictObject({baseBranch:z.string().min(1).max(200).regex(/^[a-zA-Z0-9][a-zA-Z0-9_./-]*$/).refine(v=>!v.includes('..')&&!v.includes('//')&&!v.endsWith('/')&&!v.endsWith('.lock')),directory:z.string().min(1).max(200),title:z.string().trim().min(1).max(200)});
export const gitSha=z.string().regex(/^[a-f0-9]{40}$/);
export async function gitBlobSha(bytes:Uint8Array){return Buffer.from(await crypto.subtle.digest('SHA-1',new Uint8Array(Buffer.concat([Buffer.from(`blob ${bytes.length}\0`),Buffer.from(bytes)])))).toString('hex');}
export async function reactArchiveFiles(bytes:Uint8Array,directory:string){
  githubSourcePath(directory);if(directory.split('/').some(part=>part==='.github'))fail(400,'unsafe_destination','Choose a directory outside GitHub workflows.');
  const archive=await JSZip.loadAsync(bytes),files:{path:string;bytes:Uint8Array;sha:string}[]=[];let total=0;
  const entries=Object.values(archive.files).filter(file=>!file.dir);
  if(!entries.length||entries.length>500)fail(413,'limit_exceeded','React export has too many files.');
  for(const entry of entries){
    const unsafe=(entry as typeof entry&{unsafeOriginalName?:string}).unsafeOriginalName;
    if(unsafe&&unsafe!==entry.name)fail(400,'unsafe_destination','Archive contains a rewritten path.');
    const path=githubSourcePath(`${directory}/${entry.name}`);
    if(path.split('/').includes('.github'))fail(400,'unsafe_destination','Workflow files cannot be exported.');
    // Archive bytes are generated by Studio; sizes are bounded again before preparing any remote request.
    const content=await entry.async('uint8array');total+=content.length;
    if(content.length>2097152||total>20971520)fail(413,'limit_exceeded','Reduce the React export size.');
    files.push({path,bytes:content,sha:await gitBlobSha(content)});
  }
  return files;
}
export async function githubBase(env:Bindings,base:string,token:string,branch:string,commit:string){
  const ref=z.object({object:z.object({sha:gitSha})}).parse(await nativeJson(env,`${base}/git/ref/heads/${branch.split('/').map(encodeURIComponent).join('/')}`,{headers:githubHeaders(token)}));
  if(ref.object.sha!==commit)fail(409,'revision_conflict','The base branch moved. Select its current commit and review a new diff.');
  const pinned=z.object({sha:z.literal(commit),tree:z.object({sha:gitSha})}).parse(await nativeJson(env,`${base}/git/commits/${commit}`,{headers:githubHeaders(token)}));
  return pinned.tree.sha;
}
export async function stageGithubExport(c:Context<Env>,operation:ConnectorOperation,args:z.infer<typeof githubExportArguments>,remote:{repository:{full_name:string};token:string},commit:string){
  if(await exportArtifact(c.env,operation.id))return;
  const base=`https://api.github.com/repos/${remote.repository.full_name}`,treeSha=await githubBase(c.env,base,remote.token,args.baseBranch,commit);
  const response=await renderProjectExport(c,operation.projectId,{format:'react',expectedRevision:operation.versions.documentRevision});
  const bytes=new Uint8Array(await limitedBytes(response,20971520)),files=await reactArchiveFiles(bytes,args.directory);
  const tree=z.object({truncated:z.literal(false),tree:z.array(z.object({path:z.string(),sha:gitSha,type:z.string(),mode:z.string()})).max(20000)}).parse(await nativeJson(c.env,`${base}/git/trees/${treeSha}?recursive=1`,{headers:githubHeaders(remote.token)},2097152));
  const existing=new Map(tree.tree.map(entry=>[entry.path,entry])),diff=[];
  for(const file of files){
    const parts=file.path.split('/');for(let i=1;i<parts.length;i++){const parent=existing.get(parts.slice(0,i).join('/'));if(parent&&parent.type!=='tree')fail(400,'unsafe_destination','Export path crosses an existing file, symlink or submodule.');}
    const before=existing.get(file.path);
    if(before&&(before.type!=='blob'||!['100644','100755'].includes(before.mode)))fail(400,'unsafe_destination','Export would replace a directory, symlink or submodule.');
    if(before?.sha!==file.sha)diff.push({path:file.path,change:before?'modified':'added',beforeSha:before?.sha??null,afterSha:file.sha,bytes:file.bytes.length});
  }
  if(!diff.length)fail(409,'no_changes','The selected base already contains this React export.');
  const hash=Buffer.from(await crypto.subtle.digest('SHA-256',bytes)).toString('hex'),branch=`studio/export-${operation.id}`;
  const result=await encrypt(c.env,JSON.stringify({operationId:operation.id,userId:operation.principal.userId,result:{review:{repository:remote.repository.full_name,baseBranch:args.baseBranch,baseCommit:commit,baseTree:treeSha,branch,directory:args.directory,archiveSha256:hash,files:diff,deletions:[],notice:'Download the prepared ZIP to inspect complete new file contents. Existing unrelated files are preserved.'}}}));
  const upload=await beginConnectorObjectUpload(c.env);
  try{
    await c.env.ASSETS_BUCKET.put(upload.key,bytes);
    const row=await c.env.DB.prepare('SELECT binding_id FROM connector_operations WHERE id=? AND user_id=?').bind(operation.id,operation.principal.userId).first<{binding_id:string}>();if(!row)fail(409,'revision_conflict','Export operation was removed.');
    const authority=await inspectOperationVersions(c.env,operation.principal,row.binding_id,operation.versions,'write',operation.action);
    await c.env.DB.batch([
      c.env.DB.prepare(`INSERT INTO connector_export_artifacts(operation_id,object_key,content_hash,mime_type,bytes,remote_id) SELECT ?,?,?,'application/zip',?,? WHERE EXISTS(SELECT 1 FROM connector_operations WHERE id=? AND status='awaiting_approval' AND encrypted_arguments IS NOT NULL) AND EXISTS(SELECT 1 FROM connector_object_cleanup WHERE object_key=? AND lease_id=? AND state='uploading' AND due_at>?) AND (${authority.guard.sql}) ON CONFLICT DO NOTHING`).bind(operation.id,upload.key,hash,bytes.length,branch,operation.id,upload.key,upload.lease,Date.now(),...authority.guard.values),
      c.env.DB.prepare("UPDATE connector_operations SET encrypted_result=? WHERE id=? AND status='awaiting_approval' AND EXISTS(SELECT 1 FROM connector_export_artifacts WHERE operation_id=? AND object_key=?)").bind(result,operation.id,operation.id,upload.key),
      c.env.DB.prepare('DELETE FROM connector_object_cleanup WHERE object_key=? AND lease_id=? AND EXISTS(SELECT 1 FROM connector_export_artifacts WHERE operation_id=? AND object_key=?)').bind(upload.key,upload.lease,operation.id,upload.key),
    ]);
    if((await exportArtifact(c.env,operation.id))?.object_key!==upload.key){await abandonConnectorObjectUpload(c.env,upload.key,upload.lease);if(!await exportArtifact(c.env,operation.id))fail(409,'revision_conflict','Export authority changed while preparing.');}
  }catch(error){await abandonConnectorObjectUpload(c.env,upload.key,upload.lease);throw error;}
}
export async function preparedGithubFiles(env:Bindings,operationId:string,directory:string){const value=await readExportArtifact(env,operationId);return {...value,files:await reactArchiveFiles(value.bytes,directory)};}
